version: 2
jobs:
  build:
    docker:
      - image: applift/circle_ci_docker_image:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

    steps:
      - checkout
      - setup_remote_docker
      - run: /build_docker_image.sh
      - run: /upload_to_marathon.sh
